CREATE TABLE cars (
                      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      brand       VARCHAR(255) NOT NULL,
                      model       VARCHAR(255) NOT NULL,
                      engine_code VARCHAR(255),
                      horse_power INTEGER      NOT NULL,
                      year        INTEGER      NOT NULL,
                      owner_id    BIGINT,
                      CONSTRAINT fk_cars_owner FOREIGN KEY (owner_id) REFERENCES owners (id)
);

CREATE INDEX idx_cars_brand ON cars (LOWER(brand));