CREATE TABLE users (
                       id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username      VARCHAR(255) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL,
                       role          VARCHAR(255)
);

INSERT INTO users (username, password_hash, role)
VALUES ('admin', '$2a$10$987UMjamFocD1fefsvWCr.DRx9QonZbY6Mn8N.YPF0JHs5ZS4.PLa', 'ADMIN');